### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Pachuquero** [Steve0verton/qr-business-card#1]
Extremely useful. I'd like to request the possibility of adding a logo. 

I was recommended to use the _free_ Blinq app, which I found out adds four trackers...

**Comment by Pachuquero** [comment]
Come to think of it, it would be great to also be able to add an address. 

Cheers and thanks!

**Comment by Steve0verton** [comment]
Sounds good, I will work on that this week!

**Comment by Steve0verton** [comment]
@Pachuquero check out the address additions, let me know what you think. I had to make a lot of additional updates to bring Bootstrap CSS up to the latest.  Also had to figure out all of the variations in address fields to manage. Working on image upload now.

**Comment by Pachuquero** [comment]
Hi Steve,

It looks great - and I'm delighted that you included both *home *and *business
*phones & addresses.

Though I don't presently need a business address, I now use two QRs on my
phone - with and w/o my home address, depending on whom I'm dealing with.
This I find extremely convenient for quick exchange of contact data!

I think it would be very useful to be able to also share one's location
with a link that will open a navigation and/or map app (e.g. Waze, Open
Street Map, Google Map, etc.). Here in Costa Rica most of us depend on
Waze, which can generate such a link to be put in your QR (so far that's
what I did with my email signature).

Related to this is that at least Google's Contacts will automatically offer
a Google Map link in its address book - assuming it can connect the two.
However, here in Costa Rica physical addresses are somewhat of a mess so
we're better off simply manually finding coordinates and manually adding an
appropriate link stating what app will open it.

I don't know if the vCard standard can accommodate such a feature and - if
not - one can simply add it to the address field - assuming there is
enough space (as I've done in the example below in Google Contacts).

[image: From Google Contacts.jpg]

I suppose that the vCard standard includes *Notes *so that would be another
place to put such a geographic link. If these solutions are clickable I
don't know....?

A final comment has to do with the *image *upload. In my case it would be
for a logo, which I suppose would  apply for most businesses. I do
not-for-profit natural resource GIS work. Either way if it can enter a
given address book that would be smashing!

Thanks again for all the good work! I've already recommended to friends
your https://qrbizcard.net

Have a nice day,

Micael

**Comment by Steve0verton** [comment]
Awesome! Glad it is helpful, this is a basic tool I decided to build to help people out.  Using a QR code as a native business card is such a cool thing for networking and business purposes.  I'm happy you (and others) are getting use from it!

Check out the TODO.md list at the root. I did add Notes and plenty of other things I'm going to work on also.  I'll close this Issue out once I get the contact photo upload thing working, it is a little more challenging.  Working on the photo upload thing now, trying to use what the Bootstrapped CSS provides, but also have to write up some Javascript so everything happens right in the browser (nothing to actually upload!).

Feel free to load up more issues to add anything missing!

**Comment by Pachuquero** [comment]
I just found out that if I exclude input for *State *then the whole address
disappears from the QR. Since Costa Rica is not a federation a *State* does
not apply here. We do have Provinces though but it may be ambiguous in this
case to add it, since that is also the name of the capital.

P.S.: just got your response. I surely will check out the Todo list. Cheers
mate!

**Comment by Steve0verton** [comment]
@Pachuquero bad news, I don't think embedding a photo is worthwhile. I'm getting errors from the QR generation API, because the request body is too large (due to the base64 encoding of the image).  I finally got it working, but the large amount of data makes the API request fail.  

I could try switching to a POST request to generate (reference link below), but I feel like the QR image itself will become too large and not be productive for the smaller use cases of a "virtual business card" because the QR code would have to be physically printed very large.
https://developers.google.com/chart/image/docs/post_requests

More info on large requests: 
https://developers.google.com/chart/image/faq?csw=1#url_length

I'm going to mark this issue as closed.  Please continue to create other issues as new ideas come up! (That's aren't already on the TODO list...)
